### ISSUE TITLE
使用vitepress-plugin-rss 在打包时出现问题 cdata.replace is not a function

### ISSUE THREAD

**Issue by Truraly** [ATQQ/sugar-blog#279]
你好，我在使用vitepress-plugin-rss这个包来实现网站的RSS更新，但是我在打包时出现了如下错误

```
build error:
cdata.replace is not a function
TypeError: cdata.replace is not a function
    at writeCdata (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:111:142)
    at writeElementsCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:292:116)
    at writeElementCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:295:73)
    at writeElementCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:295:73)
    at writeElementCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:295:73)
    at writeElementCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/home/truraly/TPARA/Notes/blogs/node_modules/xml-js/lib/js2xml.js:295:73)
```

经过详细的寻找`package-lock.json` 我发现了其中的依赖关系 xml-js -> feed -> vitepress-plugin-rss

`package-lock.json` 部分截取如下：

> 没有其他的依赖关系了

```json
    "node_modules/feed": {
      "version": "4.2.2",
      "license": "MIT",
      "dependencies": {
        "xml-js": "^1.6.11"
      },
      "engines": {
        "node": ">=0.4.0"
      }
    },
    "node_modules/xml-js": {
      "version": "1.6.11",
      "license": "MIT",
      "dependencies": {
        "sax": "^1.2.4"
      },
      "bin": {
        "xml-js": "bin/cli.js"
      }
    },
    "node_modules/vitepress-plugin-rss": {
      "version": "0.2.9",
      "license": "MIT",
      "dependencies": {
        "@sugarat/theme-shared": "0.0.2",
        "fast-glob": "^3.2.12",
        "feed": "^4.2.2"
      },
      "peerDependencies": {
        "vitepress": "^1"
      }
    },
```

我的能力无法解决这个错误，我认为应该是这个插件导致的错误。

其余可能有用的信息

OS: Kubuntu 22.04.4 LTS x86_64 
Kernel: 6.5.0-45-generic 
CPU: AMD Ryzen 5 5600H with Radeon Graphics (12) @ 4.280GHz 
GPU: AMD ATI 06:00.0 Cezanne 
GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
Memory: 27905MiB 
node：v21.5.0

**Comment by ATQQ** [comment]
你可以提供一下能复现问题的仓库吗

**Comment by ATQQ** [comment]
好滴，我下来也试试按你这个说法。

**Comment by ATQQ** [comment]
我这边没有复现这个问题，你有空看看换成 pnpm 会不会有这个问题。我看 xml-js 和 feed 这2个库确实很久没有有更新了。

<img width="827" alt="image" src="https://github.com/user-attachments/assets/05f7ffec-d4f1-46c4-b7be-8b7716d8b9ae">

**Comment by Truraly** [comment]
发现似乎不是文件名而是前言里的问题
> 我在创建的时候会使用脚本，创建和文件名相同title前言

you can try this
```md
---
title: 1
---

# test

test1
```

**Comment by ATQQ** [comment]
ok 我复现了，应该是 title 设置为数字，解析后 被当做字符串操作导致的问题，我看看处理一下。

**Comment by ATQQ** [comment]
vitepress-plugin-rss@0.2.10

修了这个问题😋
