### ISSUE TITLE
vitepress-plugin-rss 打包的时候，会出现问题

### ISSUE THREAD

**Issue by Aurorxa** [ATQQ/sugar-blog#323]
问题截图：
![image](https://github.com/user-attachments/assets/78c847a6-4a0e-4247-b23d-ddd93a4a656b)

报错信息：
```
Cannot read properties of undefined (reading 'path')
TypeError: Cannot read properties of undefined (reading 'path')
    at md2.render (file:///D:/project/github-notes/c/docs/.vitepress/config.mts.timestamp-1735201327543-1db90d42b612a.mjs:147:34)
    at file:///D:/project/github-notes/c/node_modules/.pnpm/vitepress-plugin-rss@0.3.0_vitepress@1.5.0_@algolia+client-search@5.18.0_@types+node@22.10.2__iz5b7ujwt7iudct3zl6n2i7xqi/node_modules/vitepress-plugin-rss/dist/index.mjs:129:27
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/project/github-notes/c/node_modules/.pnpm/vitepress-plugin-rss@0.3.0_vitepress@1.5.0_@algolia+client-search@5.18.0_@types+node@22.10.2__iz5b7ujwt7iudct3zl6n2i7xqi/node_modules/vitepress-plugin-rss/dist/index.mjs:33:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

node 版本是：
v22.12.0

**Comment by ATQQ** [comment]
可以来个可复现的仓库

**Comment by Aurorxa** [comment]
> 可以来个可复现的仓库
https://super-enigma-xrpxr7rgv45hg7v.github.dev/  这是 github codespace 的环境，node 都配置好了

https://github.com/Aurorxa/c.git    git 仓库

**Comment by ATQQ** [comment]
今天有空看了一下，错误的逻辑在你的 md.render ，里面取 env 逻辑在插件里 render的时候没有对应值传入

<img width="803" alt="Image" src="https://github.com/user-attachments/assets/3c8e942f-7ffa-47bf-9e43-f4d011742a86" />


我在插件里把相关 env 生成注入一下 应该就可以了

<img width="738" alt="Image" src="https://github.com/user-attachments/assets/ecee1dd6-9e19-4cd6-9793-6993a76a7f03" />

**Comment by Aurorxa** [comment]
OK，谢谢，我一会试试

**Comment by ATQQ** [comment]
vitepress-plugin-rss@0.3.1
